[features]
seeds = false
skip-lint = false
[programs.devnet]
nft_market = "CZN8YRNd6ki7WWKomYKFxuH6TZtiMPuQjauxsgHYSwjj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jsunnykhan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
